export const TRAMITE = {
  CREATE: "/tramite/create/",
  CREATE_EMITIDO: "/tramite/create_emitido/",
  RECIBIR_EXTERNO: "/tramite/recibir_externo/",
  RECIBIR: "/tramite/recibir/",
  DESMARCAR_RECIBIR: "/tramite/desmarcar_recibir/",
  ATENDER: "/tramite/atender/",
  ATENDER2: "/tramite/atender2/",
  DERIVAR: "/tramite/derivar/",
  DESMARCAR_ATENDER: "/tramite/desmarcar_atender/",
  OBSERVAR: "/tramite/observar/",
  DESMARCAR_OBSERVAR: "/tramite/desmarcar_observar/",
  ARCHIVAR: "/tramite/archivar/",
  DESMARCAR_ARCHIVAR: "/tramite/desmarcar_archivar/",
  FIND_ALL: "/tramite/find_all/",
  FIND_ALL_PENDIENTES: "/tramite/find_all_pendientes/",
  FIND_ALL_RECIBIDOS: "/tramite/find_all_recibidos/",
  FIND_ONE: "/tramite/find_one/",
  UPDATE: "/tramite/update/",
  REMOVE: "/tramite/remove/",
};
