export const TRAMITE = {
  CREATE: "/tramite/create/",
  CREATE_EMITIDO: "/tramite/create_emitido/",
  RECIBIR_EXTERNO: "/tramite/recibir_externo/",
  RECIBIR: "/tramite/recibir/",
  ATENDER: "/tramite/atender/",
  DESMARCAR_ATENDER: "/tramite/desmarcar_atender/",
  OBSERVAR: "/tramite/observar/",
  DESMARCAR_OBSERVAR: "/tramite/desmarcar_observar/",
  FIND_ALL: "/tramite/find_all/",
  FIND_ALL_PENDIENTES: "/tramite/find_all_pendientes/",
  FIND_ALL_RECIBIDOS: "/tramite/find_all_recibidos/",
  FIND_ONE: "/tramite/find_one/",
  UPDATE: "/tramite/update/",
  REMOVE: "/tramite/remove/",
};
